// <auto-generated />
using Magazine_Web_Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Magazine_Web_Api.Migrations
{
    [DbContext(typeof(DergiContext))]
    [Migration("20220811203450_ilk1")]
    partial class ilk1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Magazine_Web_Api.Models.Dergi", b =>
                {
                    b.Property<int>("DergiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DergiAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YayinPeriyodu")
                        .HasColumnType("int");

                    b.Property<int>("YayinTuru")
                        .HasColumnType("int");

                    b.Property<string>("İmtiyazSahibi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DergiId");

                    b.ToTable("Dergi");
                });
#pragma warning restore 612, 618
        }
    }
}
